### ISSUE TITLE
date/time example is wrong

### ISSUE THREAD

**Issue by OriHoch** [hasadna/open-bus-stride-api#13]
the date/time examples shows hour `55`

![image](https://user-images.githubusercontent.com/1198854/167369205-81de51c4-7042-4d9b-a716-40986c34bd09.png)

**Comment by shootermv** [comment]
what endpoint has a problematic docs? is it `/gtfs_ride_stops/list`?

**Comment by OriHoch** [comment]
all endpoints have this problem, including `/gtfs_ride_stops/list`

**Comment by shootermv** [comment]
i can see - the endpoint returns data when passing date time values...
![image](https://github.com/hasadna/open-bus-stride-api/assets/1336862/a8762c7d-9f52-4c25-9689-c7e990895d12)
which means - the problem not exists? or im missing something?

**Comment by OriHoch** [comment]
the problem is in the /docs endpoint - 

![image](https://github.com/hasadna/open-bus-stride-api/assets/1198854/da3379f1-5c80-4d7c-bf1a-756cbfb5bb7e)

**Comment by shootermv** [comment]
now i can see - the problem is with field `gtfs_ride__start_time_from`
it says in the docs it should get `date-time` values, but when such value passed - the swagger throws validation error...

**Comment by shootermv** [comment]
the question is - what kind of change is needed?
is the field actually getting some other type of value? (like `10:30`)
or - there is some error and field should get datetime value (as docs say)?

**Comment by OriHoch** [comment]
need to fix the example to show a valid date/time with normal hour (e.g. instead of `55` show hour `15`)
