### ISSUE TITLE
endpoint not working - gtfs_ride_stops/list?gtfs_ride_ids=<id>

### ISSUE THREAD

**Issue by NoamGaash** [hasadna/open-bus-stride-api#26]
the endpoint -
https://open-bus-stride-api.hasadna.org.il/gtfs_ride_stops/list?gtfs_ride_ids=42934600
keeps the client side hanging without a response.
removing the `gtfs_ride_ids` field works just fine

**Comment by OriHoch** [comment]
@NoamGaash This results in a heavy query on the DB, I suggest to always add gtfs date ranges to your your queries, then it will return very fast:

https://open-bus-stride-api.hasadna.org.il/gtfs_ride_stops/list?gtfs_ride_ids=42934600&gtfs_stop__date_from=2023-05-20&gtfs_stop__date_to=2023-05-30&gtfs_route__date_from=2023-05-20&gtfs_route__date_to=2023-05-30

**Comment by ShayAdler** [comment]
@NoamGaash just as thinking of ideas for small donations, do you think it would be helpful to add a limit in the API for that (fail immediately when not enough filters are supplied?)

**Comment by NoamGaash** [comment]
That's a great idea. It should be implemented to return error `400`

**Comment by ohaval** [comment]
Hey, I want to take and work on this little issue.

**Comment by NoamGaash** [comment]
@ohaval great, thanks!

**Comment by OriHoch** [comment]
@ohaval you can contact me on hasadna slack if you want guidance / help with this task

**Comment by OriHoch** [comment]
fixed in #42

**Comment by NoamGaash** [comment]
Thanks, but seems like we're now having a frontend problem:
![image](https://github.com/hasadna/open-bus-stride-api/assets/11145132/b4ee0963-4ad4-438e-9884-96f08a3bb953)
![image](https://github.com/hasadna/open-bus-stride-api/assets/11145132/52dc12c4-df33-45d6-924d-1a45a8a1162c)

Did #42 changed this api?
https://open-bus-stride-api.hasadna.org.il/gtfs_ride_stops/list?gtfs_ride_ids=66912328
It used to work

https://open-bus-map-search.hasadna.org.il/timeline?timestamp=1707742801451&operatorId=3&lineNumber=1&routeKey=%D7%94%D7%A0%D7%93%D7%99%D7%91%2F%D7%94%D7%9E%D7%99%D7%99%D7%A1%D7%93%D7%99%D7%9D-%D7%96%D7%9B%D7%A8%D7%95%D7%9F+%D7%99%D7%A2%D7%A7%D7%91%3C-%3E%D7%94%D7%A0%D7%93%D7%99%D7%91%2F%D7%94%D7%9E%D7%99%D7%99%D7%A1%D7%93%D7%99%D7%9D-%D7%96%D7%9B%D7%A8%D7%95%D7%9F+%D7%99%D7%A2%D7%A7%D7%91-3%D7%97

**Comment by OriHoch** [comment]
@NoamGaash @ohaval fixed to allow requests for a specific gtfs ride id
