### ISSUE TITLE
duplicate results at routes request

### ISSUE THREAD

**Issue by shootermv** [hasadna/open-bus-stride-api#32]
https://open-bus-stride-api.hasadna.org.il/gtfs_routes/list?limit=100&date_from=2023-11-01&date_to=2023-11-01&operator_refs=4&route_short_name=364
the routes has different number s at the endings, but they actually the same route
![image](https://github.com/hasadna/open-bus-stride-api/assets/1336862/c04f793e-40b8-46c7-a2d5-0e99cf5ee044)

**Comment by OriHoch** [comment]
hi, thanks for the bug, good to see you here!

the gtfs_* methods expose the raw data as we get it from the MOT (משרד התחבורה) - in this case there is no duplication - there are 2 different routes, one with route_alternative='#' and one with route_alternative='4' - each one has different rides related to it

it might make sense when getting data for end-users to combine them, but this should not be exposed in this method, but a new method which might handle the logic differently - combining all the route alternatives to be displayed as 1 logical route, or maybe combine routes based on the route short name.

**Comment by shootermv** [comment]
Glad to see you again Ori!
for that you said i understood there is a need to create one more endpoint
endpoint that combine routes based on the route short name
am i right?
if so - does it mean we should open a special issue for this?

**Comment by OriHoch** [comment]
yes
