### ISSUE TITLE
siri_rides/list missing some results

### ISSUE THREAD

**Issue by royeldar** [hasadna/open-bus-stride-api#41]
Hi,

when trying to use `siri_rides/list` for getting all rides of a given line today,
I get an empty list (albeit it working for yesterday and the days before).

However, when I use `siri_rides/get` for a ride that occurs today, it works.

I noticed that this seems to happen because some fields, such as `gtfs_ride_id`,
are null, so when the gtfs columns are joined to the siri rides, the list becomes empty;
see https://github.com/hasadna/open-bus/issues/404.

There was a very similar issue regarding `siri_ride_stops/list`;
see https://github.com/hasadna/open-bus-stride-client/issues/8.

It was fixed by changing some joins to outerjoins in `siri_ride_stops.py`,
and I think a very similar change can be done as well in `siri_rides.py`;
something like the following (it hasn't been tested, though):

```patch
@@ -63,8 +63,8 @@ def _post_session_query_hook(session_query: sqlalchemy.orm.Query):
     return (
         session_query
         .join(model.SiriRoute, model.SiriRide.siri_route_id == model.SiriRoute.id)
-        .join(model.GtfsRide, model.SiriRide.gtfs_ride_id == model.GtfsRide.id)
-        .join(model.GtfsRoute, model.GtfsRide.gtfs_route_id == model.GtfsRoute.id)
+        .outerjoin(model.GtfsRide, model.SiriRide.gtfs_ride_id == model.GtfsRide.id)
+        .outerjoin(model.GtfsRoute, model.GtfsRide.gtfs_route_id == model.GtfsRoute.id)
     )
```

Thanks!

**Comment by OriHoch** [comment]
thanks, fixed
